name: Generate Daily Post

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate post
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Starting post generation..."
        python content/generate_post.py
        if [ $? -eq 0 ]; then
          echo "Post generation completed successfully"
        else
          echo "Post generation failed"
          exit 1
        fi
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
    
    - name: Commit and push if changed
      run: |
        git add .
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Changes detected, committing and pushing..."
          git commit -m "Add new post [skip ci]"
          git push
        fi 